version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: sw-backend
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=docker
      - VITE_API_URL=http://backend:80
    image: sw-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
